if (NOT THIRDPARTY_BINARY_DIR)
    set(THIRDPARTY_BINARY_DIR "${CMAKE_BINARY_DIR}/thirdparty")
endif()
if (NOT THIRDPARTY_INSTALL_PREFIX)
    set(THIRDPARTY_INSTALL_PREFIX "${THIRDPARTY_BINARY_DIR}/prefix")
endif()
file(MAKE_DIRECTORY ${THIRDPARTY_BINARY_DIR})

execute_process(
    COMMAND ${CMAKE_COMMAND} ${CMAKE_SOURCE_DIR}/thirdparty -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${THIRDPARTY_INSTALL_PREFIX}
    WORKING_DIRECTORY ${THIRDPARTY_BINARY_DIR}
    RESULT_VARIABLE THIRDPARTY_CONFIGURE_STATUS
)
if (NOT ${THIRDPARTY_CONFIGURE_STATUS} EQUAL 0)
    message(FATAL_ERROR "Failed to configure thirdparty dependencies.")
endif()

execute_process(
    COMMAND ${CMAKE_COMMAND} --build ${THIRDPARTY_BINARY_DIR}
    WORKING_DIRECTORY ${THIRDPARTY_BINARY_DIR}
    RESULT_VARIABLE THIRDPARTY_BUILD_STATUS
)
if (NOT ${THIRDPARTY_BUILD_STATUS} EQUAL 0)
    message(FATAL_ERROR "Failed to build thirdparty dependencies.")
endif()

set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} ${THIRDPARTY_INSTALL_PREFIX})

find_package(glfw3 3.2.1 REQUIRED)
find_package(OpenGL REQUIRED)
find_package(glm REQUIRED)
find_package(PythonLibs REQUIRED)

add_library(zlib STATIC IMPORTED)
set_property(TARGET zlib PROPERTY IMPORTED_LOCATION ${THIRDPARTY_INSTALL_PREFIX}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}z${CMAKE_STATIC_LIBRARY_SUFFIX})

add_library(libpng STATIC IMPORTED)
set_property(TARGET libpng PROPERTY IMPORTED_LOCATION ${THIRDPARTY_INSTALL_PREFIX}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}png${CMAKE_STATIC_LIBRARY_SUFFIX})
set_property(TARGET libpng PROPERTY INTERFACE_LINK_LIBRARIES zlib)

add_library(gtest STATIC IMPORTED)
set_property(TARGET gtest PROPERTY IMPORTED_LOCATION ${THIRDPARTY_INSTALL_PREFIX}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}gtest${CMAKE_STATIC_LIBRARY_SUFFIX})
set_property(TARGET gtest PROPERTY IMPORTED_LINK_INTERFACE_LIBRARIES pthread)

add_library(gtest_main STATIC IMPORTED)
set_property(TARGET gtest_main PROPERTY IMPORTED_LOCATION ${THIRDPARTY_INSTALL_PREFIX}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}gtest_main${CMAKE_STATIC_LIBRARY_SUFFIX})
set_property(TARGET gtest_main PROPERTY IMPORTED_LINK_INTERFACE_LIBRARIES gtest)

add_library(zeromq SHARED IMPORTED)
set_property(TARGET zeromq PROPERTY IMPORTED_LOCATION ${THIRDPARTY_INSTALL_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}zmq${CMAKE_SHARED_LIBRARY_SUFFIX})
