#ifndef GL_INTERACTIVITY_KEYCODES_H
#define GL_INTERACTIVITY_KEYCODES_H

#include <GLFW/glfw3.h>

#define EGS_RELEASE                GLFW_RELEASE
#define EGS_PRESS                  GLFW_PRESS
#define EGS_REPEAT                 GLFW_REPEAT

#define EGS_KEY_UNKNOWN            GLFW_KEY_UNKNOWN

#define EGS_KEY_SPACE              GLFW_KEY_SPACE
#define EGS_KEY_APOSTROPHE         GLFW_KEY_APOSTROPHE
#define EGS_KEY_COMMA              GLFW_KEY_COMMA
#define EGS_KEY_MINUS              GLFW_KEY_MINUS
#define EGS_KEY_PERIOD             GLFW_KEY_PERIOD
#define EGS_KEY_SLASH              GLFW_KEY_SLASH
#define EGS_KEY_0                  GLFW_KEY_0
#define EGS_KEY_1                  GLFW_KEY_1
#define EGS_KEY_2                  GLFW_KEY_2
#define EGS_KEY_3                  GLFW_KEY_3
#define EGS_KEY_4                  GLFW_KEY_4
#define EGS_KEY_5                  GLFW_KEY_5
#define EGS_KEY_6                  GLFW_KEY_6
#define EGS_KEY_7                  GLFW_KEY_7
#define EGS_KEY_8                  GLFW_KEY_8
#define EGS_KEY_9                  GLFW_KEY_9
#define EGS_KEY_SEMICOLON          GLFW_KEY_SEMICOLON
#define EGS_KEY_EQUAL              GLFW_KEY_EQUAL
#define EGS_KEY_A                  GLFW_KEY_A
#define EGS_KEY_B                  GLFW_KEY_B
#define EGS_KEY_C                  GLFW_KEY_C
#define EGS_KEY_D                  GLFW_KEY_D
#define EGS_KEY_E                  GLFW_KEY_E
#define EGS_KEY_F                  GLFW_KEY_F
#define EGS_KEY_G                  GLFW_KEY_G
#define EGS_KEY_H                  GLFW_KEY_H
#define EGS_KEY_I                  GLFW_KEY_I
#define EGS_KEY_J                  GLFW_KEY_J
#define EGS_KEY_K                  GLFW_KEY_K
#define EGS_KEY_L                  GLFW_KEY_L
#define EGS_KEY_M                  GLFW_KEY_M
#define EGS_KEY_N                  GLFW_KEY_N
#define EGS_KEY_O                  GLFW_KEY_O
#define EGS_KEY_P                  GLFW_KEY_P
#define EGS_KEY_Q                  GLFW_KEY_Q
#define EGS_KEY_R                  GLFW_KEY_R
#define EGS_KEY_S                  GLFW_KEY_S
#define EGS_KEY_T                  GLFW_KEY_T
#define EGS_KEY_U                  GLFW_KEY_U
#define EGS_KEY_V                  GLFW_KEY_V
#define EGS_KEY_W                  GLFW_KEY_W
#define EGS_KEY_X                  GLFW_KEY_X
#define EGS_KEY_Y                  GLFW_KEY_Y
#define EGS_KEY_Z                  GLFW_KEY_Z
#define EGS_KEY_LEFT_BRACKET       GLFW_KEY_LEFT_BRACKET
#define EGS_KEY_BACKSLASH          GLFW_KEY_BACKSLASH
#define EGS_KEY_RIGHT_BRACKET      GLFW_KEY_RIGHT_BRACKET
#define EGS_KEY_GRAVE_ACCENT       GLFW_KEY_GRAVE_ACCENT
#define EGS_KEY_WORLD_1            GLFW_KEY_WORLD_1
#define EGS_KEY_WORLD_2            GLFW_KEY_WORLD_2

#define EGS_KEY_ESCAPE             GLFW_KEY_ESCAPE
#define EGS_KEY_ENTER              GLFW_KEY_ENTER
#define EGS_KEY_TAB                GLFW_KEY_TAB
#define EGS_KEY_BACKSPACE          GLFW_KEY_BACKSPACE
#define EGS_KEY_INSERT             GLFW_KEY_INSERT
#define EGS_KEY_DELETE             GLFW_KEY_DELETE
#define EGS_KEY_RIGHT              GLFW_KEY_RIGHT
#define EGS_KEY_LEFT               GLFW_KEY_LEFT
#define EGS_KEY_DOWN               GLFW_KEY_DOWN
#define EGS_KEY_UP                 GLFW_KEY_UP
#define EGS_KEY_PAGE_UP            GLFW_KEY_PAGE_UP
#define EGS_KEY_PAGE_DOWN          GLFW_KEY_PAGE_DOWN
#define EGS_KEY_HOME               GLFW_KEY_HOME
#define EGS_KEY_END                GLFW_KEY_END
#define EGS_KEY_CAPS_LOCK          GLFW_KEY_CAPS_LOCK
#define EGS_KEY_SCROLL_LOCK        GLFW_KEY_SCROLL_LOCK
#define EGS_KEY_NUM_LOCK           GLFW_KEY_NUM_LOCK
#define EGS_KEY_PRINT_SCREEN       GLFW_KEY_PRINT_SCREEN
#define EGS_KEY_PAUSE              GLFW_KEY_PAUSE
#define EGS_KEY_F1                 GLFW_KEY_F1
#define EGS_KEY_F2                 GLFW_KEY_F2
#define EGS_KEY_F3                 GLFW_KEY_F3
#define EGS_KEY_F4                 GLFW_KEY_F4
#define EGS_KEY_F5                 GLFW_KEY_F5
#define EGS_KEY_F6                 GLFW_KEY_F6
#define EGS_KEY_F7                 GLFW_KEY_F7
#define EGS_KEY_F8                 GLFW_KEY_F8
#define EGS_KEY_F9                 GLFW_KEY_F9
#define EGS_KEY_F10                GLFW_KEY_F10
#define EGS_KEY_F11                GLFW_KEY_F11
#define EGS_KEY_F12                GLFW_KEY_F12
#define EGS_KEY_F13                GLFW_KEY_F13
#define EGS_KEY_F14                GLFW_KEY_F14
#define EGS_KEY_F15                GLFW_KEY_F15
#define EGS_KEY_F16                GLFW_KEY_F16
#define EGS_KEY_F17                GLFW_KEY_F17
#define EGS_KEY_F18                GLFW_KEY_F18
#define EGS_KEY_F19                GLFW_KEY_F19
#define EGS_KEY_F20                GLFW_KEY_F20
#define EGS_KEY_F21                GLFW_KEY_F21
#define EGS_KEY_F22                GLFW_KEY_F22
#define EGS_KEY_F23                GLFW_KEY_F23
#define EGS_KEY_F24                GLFW_KEY_F24
#define EGS_KEY_F25                GLFW_KEY_F25
#define EGS_KEY_KP_0               GLFW_KEY_KP_0
#define EGS_KEY_KP_1               GLFW_KEY_KP_1
#define EGS_KEY_KP_2               GLFW_KEY_KP_2
#define EGS_KEY_KP_3               GLFW_KEY_KP_3
#define EGS_KEY_KP_4               GLFW_KEY_KP_4
#define EGS_KEY_KP_5               GLFW_KEY_KP_5
#define EGS_KEY_KP_6               GLFW_KEY_KP_6
#define EGS_KEY_KP_7               GLFW_KEY_KP_7
#define EGS_KEY_KP_8               GLFW_KEY_KP_8
#define EGS_KEY_KP_9               GLFW_KEY_KP_9
#define EGS_KEY_KP_DECIMAL         GLFW_KEY_KP_DECIMAL
#define EGS_KEY_KP_DIVIDE          GLFW_KEY_KP_DIVIDE
#define EGS_KEY_KP_MULTIPLY        GLFW_KEY_KP_MULTIPLY
#define EGS_KEY_KP_SUBTRACT        GLFW_KEY_KP_SUBTRACT
#define EGS_KEY_KP_ADD             GLFW_KEY_KP_ADD
#define EGS_KEY_KP_ENTER           GLFW_KEY_KP_ENTER
#define EGS_KEY_KP_EQUAL           GLFW_KEY_KP_EQUAL
#define EGS_KEY_LEFT_SHIFT         GLFW_KEY_LEFT_SHIFT
#define EGS_KEY_LEFT_CONTROL       GLFW_KEY_LEFT_CONTROL
#define EGS_KEY_LEFT_ALT           GLFW_KEY_LEFT_ALT
#define EGS_KEY_LEFT_SUPER         GLFW_KEY_LEFT_SUPER
#define EGS_KEY_RIGHT_SHIFT        GLFW_KEY_RIGHT_SHIFT
#define EGS_KEY_RIGHT_CONTROL      GLFW_KEY_RIGHT_CONTROL
#define EGS_KEY_RIGHT_ALT          GLFW_KEY_RIGHT_ALT
#define EGS_KEY_RIGHT_SUPER        GLFW_KEY_RIGHT_SUPER
#define EGS_KEY_MENU               GLFW_KEY_MENU

#define EGS_KEY_LAST               GLFW_KEY_LAST

#define EGS_MOD_SHIFT           GLFW_MOD_SHIFT
#define EGS_MOD_CONTROL         GLFW_MOD_CONTROL
#define EGS_MOD_ALT             GLFW_MOD_ALT
#define EGS_MOD_SUPER           GLFW_MOD_SUPER

#define EGS_MOUSE_BUTTON_1         GLFW_MOUSE_BUTTON_1
#define EGS_MOUSE_BUTTON_2         GLFW_MOUSE_BUTTON_2
#define EGS_MOUSE_BUTTON_3         GLFW_MOUSE_BUTTON_3
#define EGS_MOUSE_BUTTON_4         GLFW_MOUSE_BUTTON_4
#define EGS_MOUSE_BUTTON_5         GLFW_MOUSE_BUTTON_5
#define EGS_MOUSE_BUTTON_6         GLFW_MOUSE_BUTTON_6
#define EGS_MOUSE_BUTTON_7         GLFW_MOUSE_BUTTON_7
#define EGS_MOUSE_BUTTON_8         GLFW_MOUSE_BUTTON_8
#define EGS_MOUSE_BUTTON_LAST      GLFW_MOUSE_BUTTON_LAST
#define EGS_MOUSE_BUTTON_LEFT      GLFW_MOUSE_BUTTON_LEFT
#define EGS_MOUSE_BUTTON_RIGHT     GLFW_MOUSE_BUTTON_RIGHT
#define EGS_MOUSE_BUTTON_MIDDLE    GLFW_MOUSE_BUTTON_MIDDLE

#define EGS_JOYSTICK_1             GLFW_JOYSTICK_1
#define EGS_JOYSTICK_2             GLFW_JOYSTICK_2
#define EGS_JOYSTICK_3             GLFW_JOYSTICK_3
#define EGS_JOYSTICK_4             GLFW_JOYSTICK_4
#define EGS_JOYSTICK_5             GLFW_JOYSTICK_5
#define EGS_JOYSTICK_6             GLFW_JOYSTICK_6
#define EGS_JOYSTICK_7             GLFW_JOYSTICK_7
#define EGS_JOYSTICK_8             GLFW_JOYSTICK_8
#define EGS_JOYSTICK_9             GLFW_JOYSTICK_9
#define EGS_JOYSTICK_10            GLFW_JOYSTICK_10
#define EGS_JOYSTICK_11            GLFW_JOYSTICK_11
#define EGS_JOYSTICK_12            GLFW_JOYSTICK_12
#define EGS_JOYSTICK_13            GLFW_JOYSTICK_13
#define EGS_JOYSTICK_14            GLFW_JOYSTICK_14
#define EGS_JOYSTICK_15            GLFW_JOYSTICK_15
#define EGS_JOYSTICK_16            GLFW_JOYSTICK_16
#define EGS_JOYSTICK_LAST          GLFW_JOYSTICK_LAST

#endif
